{
    'name': 'Bradford_IA CRM Module',
    'version': '1.0',
    'summary': 'Customized CRM for Lead Management',
    'category': 'CRM',
    'author': 'Pooja D',
    'depends': ['base','crm', 'mail','hr','sale'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/bradford_crm_lead_view.xml',
        'views/bradford_crm_employee_view.xml',
        'views/bradford_crm_salesperson_view.xml',
        # 'views/bradford_crm_contacts_view.xml',
        'views/bradford_crm_meeting_view.xml',
        'views/bradford_crm_task_view.xml',
        'views/bradford_crm_call_view.xml',
        'data/corn_jobs.xml',
        'views/bradford_crm_document_view.xml',
        'views/campaign_view.xml',
        'views/bradford_crm_notes_view.xml',
        'views/courses_view.xml',
        'views/source_view.xml',
        'views/highest_qualification_view.xml',
        'views/job_title_view.xml',
        'views/program_interested_view.xml',
        'views/substatusview.xml',
        'views/university_view.xml',
        'views/work_experience_view.xml',
        'views/bradford_crm_menu.xml',
        'data/mail_template.xml', 
    ],
    'installable': True,
    'application': True,
}
