from . import bradford_custom_lead
from . import bradford_employee
from . import substatus
from . import campaign
from . import courses
from . import highest_qualification
from . import job_title
from . import program_interested
from . import university
from . import work_experience
from . import source
from . import bradford_salesperson
from . import bradford_notes
from . import bradford_meeting
from . import bradford_document
from . import bradford_task
from . import bradford_call